name: bot-connector-to-teams

services: # https://docs.docker.com/compose/compose-file/05-services/
  app:
    image: "bot-connector-to-teams:${ImageTag}"
    ports:
      - "8100:80" # For public access, do not expose in SaaS environment!
    volumes:
      - app-data:/app/data
    healthcheck: # https://docs.docker.com/compose/compose-file/05-services/#healthcheck
      test: [ "CMD", "dotnet", "/app/BotConnectorToTeams.dll", "--healthcheck", "http://localhost/healthcheck" ]
      interval: 1m # Takes 1 minute for the first check, and then every minute
    environment:
      - AzureBot:MicrosoftAppType=${AzureBot_MicrosoftAppType}
      - AzureBot:MicrosoftAppId=${AzureBot_MicrosoftAppId}
      - AzureBot:MicrosoftAppPassword=${AzureBot_MicrosoftAppPassword}
      - AzureBot:MicrosoftAppTenantId=${AzureBot_MicrosoftAppTenantId}
      - UsuBot:BaseUrl=${UsuBot_BaseUrl}
      - UsuBot:ApiKey=${UsuBot_ApiKey}
      - UsuBot:ConnectorType=${UsuBot_ConnectorType}
      - UsuKnowledgeManager:BaseUrl=${UsuKnowledgeManager_BaseUrl}
      - UsuKnowledgeManager:DocumentUrl=${UsuKnowledgeManager_DocumentUrl}
      - License:Key=${License_Key}
      - Api:EnableDetailedErrorMessages=${Api_EnableDetailedErrorMessages}

volumes: # https://docs.docker.com/compose/compose-file/07-volumes/
  app-data:
    driver: local # Use the Docker Desktop default https://docs.docker.com/compose/compose-file/07-volumes/#driver
    # Inspect data here (Docker Desktop Windows):
    # \\wsl$\docker-desktop-data\data\docker\volumes\bot-connector-to-teams_app-data\_data
