name: bot-connector-to-teams

services: # https://docs.docker.com/compose/compose-file/05-services/
  init-app: # We allocate a directory and change the owner to "app" as a template for the actual volume mount.
    image: busybox:1.36.1-musl
    command:
      - sh
      - -c
      - mkdir -p /app/data
      - chown -R 1654:1654 /app/data
  app:
    depends_on:
      init-app:
        condition: service_completed_successfully
    image: "bot-connector-to-teams:${ImageTag}"
    ports:
      - "${PublicPort}:8080"
    volumes:
      - app-data:/app/data
    healthcheck: # https://docs.docker.com/compose/compose-file/05-services/#healthcheck
      test: [ "CMD", "dotnet", "/app/BotConnectorToTeams.dll", "--healthcheck", "http://localhost/healthcheck" ]
      interval: 1m # Takes 1 minute for the first check, and then every minute
      timeout: 1m
    environment:
      - App:PublicUrl=${App_PublicUrl}
      - AzureBot:MicrosoftAppType=${AzureBot_MicrosoftAppType}
      - AzureBot:MicrosoftAppId=${AzureBot_MicrosoftAppId}
      - AzureBot:MicrosoftAppPassword=${AzureBot_MicrosoftAppPassword}
      - AzureBot:MicrosoftAppTenantId=${AzureBot_MicrosoftAppTenantId}
      - UsuBot:BaseUrl=${UsuBot_BaseUrl}
      - UsuBot:ApiKey=${UsuBot_ApiKey}
      - UsuBot:ConnectorType=${UsuBot_ConnectorType}
      - UsuKnowledgeManager:BaseUrl=${UsuKnowledgeManager_BaseUrl}
      - UsuKnowledgeManager:DocumentUrl=${UsuKnowledgeManager_DocumentUrl}
      - Oktopus:BaseUrl=${Oktopus_BaseUrl}
      - Oktopus:ApiKey=${Oktopus_ApiKey}
      - License:Key=${License_Key}
      - Api:EnableDetailedErrorMessages=${Api_EnableDetailedErrorMessages}

volumes: # https://docs.docker.com/compose/compose-file/07-volumes/
  app-data:
    driver: local # Use the Docker Desktop default https://docs.docker.com/compose/compose-file/07-volumes/#driver
    # Inspect data here (Docker Desktop Windows):
    # \\wsl$\docker-desktop-data\data\docker\volumes\bot-connector-to-teams_app-data\_data
