apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bot-connector-to-teams.fullname" . }}
  labels:
    {{- include "bot-connector-to-teams.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bot-connector-to-teams.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bot-connector-to-teams.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bot-connector-to-teams.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ include "bot-connector-to-teams.fullname" . }}
          persistentVolumeClaim:
            claimName: {{ include "bot-connector-to-teams.fullname" . }}
      initContainers:
        - name: init-{{ .Chart.Name }} # We allocate a directory and change the owner to "app" as a template for the actual volume mount.
          image: busybox:1.36.1-musl
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - mkdir -p /app/data
            - chown -R 1654:1654 /app/data
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: "/app/data"
              name: {{ include "bot-connector-to-teams.fullname" . }}
          livenessProbe:
            httpGet:
              path: /livenesscheck
              port: http
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 3
            periodSeconds: 60
            timeoutSeconds: 60
          env:
            - name: AzureBot__MicrosoftAppType
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bot-connector-to-teams.fullname" . }}
                  key: AzureBot.MicrosoftAppType
            - name: AzureBot__MicrosoftAppId
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bot-connector-to-teams.fullname" . }}
                  key: AzureBot.MicrosoftAppId
            - name: AzureBot__MicrosoftAppPassword
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bot-connector-to-teams.fullname" . }}
                  key: AzureBot.MicrosoftAppPassword
            - name: AzureBot__MicrosoftAppTenantId
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bot-connector-to-teams.fullname" . }}
                  key: AzureBot.MicrosoftAppTenantId
            - name: UsuBot__BaseUrl
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bot-connector-to-teams.fullname" . }}
                  key: UsuBot.BaseUrl
            - name: UsuBot__ApiKey
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bot-connector-to-teams.fullname" . }}
                  key: UsuBot.ApiKey
            - name: UsuBot__ConnectorType
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bot-connector-to-teams.fullname" . }}
                  key: UsuBot.ConnectorType
            - name: UsuKnowledgeManager__BaseUrl
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bot-connector-to-teams.fullname" . }}
                  key: UsuKnowledgeManager.BaseUrl
            - name: UsuKnowledgeManager__DocumentUrl
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bot-connector-to-teams.fullname" . }}
                  key: UsuKnowledgeManager.DocumentUrl
            - name: License__Key
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bot-connector-to-teams.fullname" . }}
                  key: License.Key
            - name: Api__EnableDetailedErrorMessages
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bot-connector-to-teams.fullname" . }}
                  key: Api.EnableDetailedErrorMessages
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
